# Generated by Django 2.2.18 on 2021-03-01 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='layananAntrian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_layanan', models.CharField(max_length=2)),
                ('nama_layanan', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('foto', models.CharField(max_length=50)),
            ],
        ),
    ]
