# Generated by Django 2.2.18 on 2021-03-01 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='layananAntrian',
            new_name='Antrian',
        ),
    ]
