# Generated by Django 2.2.18 on 2021-03-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_auto_20210301_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_antrian', models.IntegerField()),
                ('jenis_layanan', models.CharField(max_length=2)),
                ('status', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
