# Generated by Django 2.2.18 on 2021-03-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0003_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='jenis_layanan',
            field=models.CharField(choices=[('BPJS', 'A'), ('Gigi', 'B'), ('Jantung', 'C')], default='A', max_length=100),
        ),
    ]
