# Generated by Django 2.2.18 on 2021-03-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0004_auto_20210301_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='jenis_layanan',
            field=models.CharField(max_length=2),
        ),
    ]
